# Random Module

In [34]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[3 2 4 9 5 1 0 7 8 6]


In [33]:
a = np.random.rand(2,3)
print(a)

a = np.random.randint(5,10,3)
print(a)

[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]
[9 6 7]


In [27]:
element = np.random.choice(a)
print(element)

5


# statiscs using numpy

## min

In [50]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [56]:
b = np.array([1,2,3,4,5])
m = sum(b)/5
print(m)

print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [57]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


# mean vs average

In [68]:
print(np.mean(c))

# weight

w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

w=np.array([1,2,3,4,5])
print(np.average(c,weights=w))

# standard deviation
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

# inbuilt function
dev = np.std(c)
print(dev)

# variance

print(mystd**2)
print(np.var(c))

2.4
2.066666666666667
2.066666666666667
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


# Linear Algebra

## 1. Scalar and vectors
* scalar isw single number denoted as **x**
* vector is an array of sacaars denoted by cx

In [107]:
import numpy as np

In [108]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [109]:
# we will represent vector as a column vector, that is having multiple rows and cp;umn
x=np.array([[4],[5],[6],[7]])
print(x)
print(x.shape)
print(x[0])
x=x.reshape((-1,2))
print(x)

[[4]
 [5]
 [6]
 [7]]
(4, 1)
[4]
[[4 5]
 [6 7]]


# 2. Matrices & Tensors
* Matrix is a 2D array of scalars. denoted by ***X***
* Tensors is an array with more than 2 axes,denoted by **X**

In [110]:
X= np.array([[4,5,7],[10,11,12],[56,80,90]])
print(X.shape)
print(X)
print(X[1][1])
X[1:,:]=2
print(X)

(3, 3)
[[ 4  5  7]
 [10 11 12]
 [56 80 90]]
11
[[4 5 7]
 [2 2 2]
 [2 2 2]]


In [111]:
# Here T is tensor
T = np.array([[[4,5,7],[10,11,13]],[[56,80,90],[9,8,10]]])
print(T.shape)

(2, 2, 3)


# 3. Transpose
For a 2D transpose can be obtained as follows (A^T)i,j=Ai,j

In [112]:
print(x)
xt = np.transpose(x)
print(xt)

y = x.reshape((-1,1))
print(y)
yt = np.transpose(y)
print(yt)
print(y.shape)
print(yt.shape)

[[4 5]
 [6 7]]
[[4 6]
 [5 7]]
[[4]
 [5]
 [6]
 [7]]
[[4 5 6 7]]
(4, 1)
(1, 4)


# 4. Brodcasting

* x+a =xi+a

In [132]:
# l=[1,2,3,4] error
# l=l**2 error

l=[1,2,3,4]
l = np.array(l)
l=l+1
print(l)
l=l**2
print(l)

l=[[1,2,3,4],[5,6,7,8]]
l=np.array(l)
l=l**2
l +=1 
print(l)

[2 3 4 5]
[ 4  9 16 25]
[[ 2  5 10 17]
 [26 37 50 65]]


In [133]:
np.sqrt(l)

array([[1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.09901951, 6.08276253, 7.07106781, 8.06225775]])

# 7. Norms

* norm(L) of a vectort =sqrt(x1^2 + x2^2+x3^2)

* pth norm (x1^p+x2^p+x**p)^(1/p)

* L2 is called Eucledian norm ||x||

* L1 norm is absolute sum of all members of a vector

* Max norm L infinity simplifies absolute value of the element with highest magnitude.

In [118]:
x = np.array([-5,3,10])
lp2 = np.linalg.norm(x)
print(lp2)

11.575836902790225


In [119]:
lp1 = np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [120]:
lpinf = np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [136]:
l=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
print(np.linalg.norm(l))

6.0
